name: Type Check

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Type Check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Check types
        run: pnpm run type-check